# Benjamin Michael Taylor (bentaylorhk)
# 2025

[general]
import = ["~/.config/alacritty/gruvbox.toml"]

[window]
title = "alacritty"
dynamic_title = false
dynamic_padding = false
decorations = "full"
#dimensions = { columns = 120, lines = 35 }
#padding = { x = 10, y = 10 }
#opacity = 0.95
#
[font]
size = 13.0

[font.bold]
family = "scientifica"
style = "Bold"

[font.bold_italic]
family = "scientifica"
style = "Bold Italic"

[font.italic]
family = "scientifica"
style = "Italic"

[font.normal]
family = "scientifica"
style = "Regular"

[cursor.style]
shape = "Block"
blinking = "On"


[scrolling]
history = 10000
multiplier = 3

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
action = "ScrollPageDown"


[terminal]

[terminal.shell]
program = "/bin/bash"
#args = ["--login"]
